stages:
  data_gathering:
    cmd: python3 src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw
  data_cleaning:
    cmd: python3 src/data/data_cleaning.py
    deps:
    - data/raw/flight_price.csv
    - src/data/data_cleaning.py
    outs:
    - data/interim
  data_transformation:
    cmd: python3 src/data/data_transformation.py
    deps:
    - data/interim/cleaned_flight_price.csv
    - src/data/data_transformation.py
    outs:
    - data/transformed
  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
    - data/transformed/transformed_flight_price.csv
    - src/features/feature_engineering.py
    outs:
    - data/features
  data_splitting:
    cmd: python3 src/model/splitting.py
    deps:
    - data/features/feature_engineered_flight_price.csv
    - src/model/splitting.py
    outs:
    - data/splitted_data
  pipeline:
    cmd: python3 -m src.model.pipeline
    deps:
    - data/splitted_data/X_train.csv
    - data/splitted_data/X_val.csv
    - data/splitted_data/X_test.csv
    - src/model/pipeline.py
  train_model_rf:
    cmd: python3 -m src.model.train_model_rf
    deps:
    - src/model/pipeline.py 
    - data/splitted_data/X_train.csv
    - data/splitted_data/y_train.csv
    - src/model/train_model_rf.py
    outs:
    - models/random_forest_model.pkl
  train_model_xgboost:
    cmd: python3 -m src.model.train_model_xgboost
    deps:
    - src/model/pipeline.py
    - data/splitted_data/X_train.csv
    - data/splitted_data/y_train.csv
    - src/model/train_model_xgboost.py
    outs:
    - models/xgboost_model.pkl
  
  evaluate_model:
    cmd: python3 -m src.model.evaluate_model
    deps:
    - models/random_forest_model.pkl
    - data/splitted_data/X_val.csv
    - data/splitted_data/y_val.csv
    - src/model/evaluate_model.py 
  hyperparameter_tuning_eval:
    cmd: python3 -m src.model.hyperparameter_tuning_eval
    deps:
    - data/splitted_data/X_train.csv
    - data/splitted_data/y_train.csv
    - data/splitted_data/X_val.csv
    - data/splitted_data/y_val.csv
    - src/model/hyperparameter_tuning_eval.py
    
