stages:
  data_gathering:
    cmd: python3 src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw
  data_cleaning:
    cmd: python3 src/data/data_cleaning.py
    deps:
    - data/raw/flight_price.csv
    - src/data/data_cleaning.py
    outs:
    - data/interim
  data_transformation:
    cmd: python3 src/data/data_transformation.py
    deps:
    - data/interim/cleaned_flight_price.csv
    - src/data/data_transformation.py
    outs:
    - data/transformed
  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
    - data/transformed/transformed_flight_price.csv
    - src/features/feature_engineering.py
    outs:
    - data/features
  data_splitting:
    cmd: python3 src/models/splliting.py
    deps:
    - data/features/feature_engineered_flight_price.csv
    - src/models/splliting.py
    outs:
    - data/splited data  
    
