test_size: 0.2
model:
  random_forest:
    n_estimators: 250
    max_depth: 20
  xgboost:
    n_estimators: 200
    max_depth: 8
    random_state: 42
    learning_rate: 0.2
hyperparameter_models:
  random_forest:
    n_estimators: [100, 200]
    max_depth: [10, 15, 20]
  xgboost:
    n_estimators: [100, 200]
    max_depth: [10, 15, 20, 25]
    learning_rate: [0.2, 0.3]